### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [Getquanty/gtm-template-gq#1]
https://github.com/Getquanty/gtm-template-gq/blob/6c33163b349b27d92e386c8efbbb12fb545b3c44/template.tpl#L71

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by vg-getquanty** [comment]
Hi,

Thanks for your message.

We can't use encodeUriComponent (see attachment) in Tag Manager, but data.site_id is only a string of numbers. This precision should allow you to validate this configuration model, I hope.

![screen](https://user-images.githubusercontent.com/83222969/146186844-aa12c41a-5f5f-4177-8cc8-49e300313ee9.png)

Best regards,
Valentin from GetQuanty

**Comment by philpott** [comment]
encodeUriComponent is only avaliable after you include it via a require call. e.g. `const encodeUriComponent = require('encodeUriComponent');`

Since it's a number its not strictly nessisary as you point out but is good to have in place so if you ever move this from a number to some other encoding scheme you don't need to think about updating this -- outside of validation.
