### ISSUE TITLE
Ensure that you want to log on clients sites

### ISSUE THREAD

**Issue by philpott** [Getquanty/gtm-template-gq#2]
https://github.com/Getquanty/gtm-template-gq/blob/6c33163b349b27d92e386c8efbbb12fb545b3c44/template.tpl#L71

With the current permissions the tag will always log when running on clients sites. It's a best practice to keep logging only when in preview mode, unless it provides benefits to your customers.

**Comment by vg-getquanty** [comment]
Hi,
We have made the necessary corrections. Could you validate the version please?

Best regards,
Valentin from GetQuanty
